### ISSUE TITLE
How to store GnuCash database in SQL

### ISSUE THREAD

**Issue by joshuabach** [joshuabach/gnucash-web#16]
We should add a quick explanation to the [README](README.md) on how to either create an empty book in an SQL database or how to migrate an existing GnuCash-XML-File into an SQL-server using the desktop client.

**Comment by coelhorb** [comment]
How to use sqlite? I've configured the system, but it doesn't find the file.

**Comment by joshuabach** [comment]
> How to use sqlite? I've configured the system, but it doesn't find the file.

What exactly have you done? Can you send me your configuration and error output?

Please note that GnuCash-Web can only open a file that was previously created using the standard GnuCash desktop app. See https://www.gnucash.org/docs/v4/C/gnucash-guide/basics-files1.html for more details.
