### ISSUE TITLE
English Demo

### ISSUE THREAD

**Issue by flywire** [joshuabach/gnucash-web#33]
Can you load an English demo file?

**Comment by joshuabach** [comment]
That would probably be a good idea :laughing:. I just used my own test-file to deploy a demo quickly.

But honestly, this is not super important to me right now, so don't expect one in the next few days.

**Comment by flywire** [comment]
Example [data](https://lists.gnucash.org/pipermail/gnucash-user/attachments/20210718/2f60caee/attachment.obj) based on GnuCash Tutorial and Concepts Guide Part II. Managing Personal Finances - https://gnucash.org/viewdoc.phtml?rev=4&lang=C&doc=guide - see [discussion](https://lists.gnucash.org/pipermail/gnucash-user/2021-July/097124.html).

**Comment by joshuabach** [comment]
Nice, thank you for that! I deployed that data to the [demo](https://gnucash-web-demo.bachmeier.cc/).
