### ISSUE TITLE
Error when root account does not have a defined commodity

### ISSUE THREAD

**Issue by williamjacksn** [joshuabach/gnucash-web#42]
```
ERROR [gnucash_web] Exception on /book/accounts/ [GET]
Traceback (most recent call last):

  ... removed ...

  File "/home/python/venv/lib/python3.11/site-packages/gnucash_web/templates/forms.j2", line 26, in template
    step="{{ 1 / account.commodity.fraction }}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'fraction'
```

I'm using a SQLite GnuCash file. Somehow my root account does not have a defined commodity.

![image](https://github.com/joshuabach/gnucash-web/assets/565174/a18decd3-592a-4ed5-9243-df2eb562f9ea)

I haven't done anything strange with this book, so I don't know if this is normal or how to correct it.

**Comment by joshuabach** [comment]
Interesting, all my books seem to have a commodity in the root account. Maybe this has to do with the books default currency. But I thought that all books had those.

Either way, this only occurs in the new/edit transaction form, which should never be generated for the root account. I think I forgot to check for that case when generating the edit-transaction form. 

See [templates/account.j2:129]( https://github.com/joshuabach/gnucash-web/blob/085a63dc9ce5d772a081f8936392567576718105/gnucash_web/templates/account.j2#LL129C28-L129C28)

So should be an easy fix.
