### ISSUE TITLE
[SUPPORT] Database 'sqlite:///db/gnucash.sqlite' does not exist

### ISSUE THREAD

**Issue by 79vette** [joshuabach/gnucash-web#50]
I'm several hours into trying to set this up, but am now stuck at an error I can't figure out.  The app is saying it cannot find the database file, and I do not understand why.  I have the database location correctly defined in the config file, and I can open the database file successfully on desktop gnuCash.  Any help would be appreciated!

**Error text**
```
2023-09-09 23:46:07,678] ERROR in app: Exception on /book/accounts/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gnucash_web/auth.py", line 62, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gnucash_web/book.py", line 79, in show_account
    with open_book(
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gnucash_web/utils/gnucash.py", line 73, in open_book
    raise e
  File "/usr/local/lib/python3.11/dist-packages/gnucash_web/utils/gnucash.py", line 66, in open_book
    with piecash.open_book(*args, **kwargs) as book:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/piecash/core/session.py", line 409, in open_book
    raise GnucashException(
piecash._common.GnucashException: Database 'sqlite:///db/gnucash.sqlite' does not exist (please use create_book to create GnuCash books from scratch). If you want to bypass this existence check, use the argument check_exists=False.
[pid: 445|app: 0|req: 1/1] 192.168.1.23 () {38 vars in 780 bytes} [Sat Sep  9 23:46:07 2023] GET /book/accounts/ => generated 265 bytes in 8 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
```

**Config File**
```
:~# cat /etc/gnucash_web/config.py
import logging

# A 32-bit-key used e.g. to encrypt the session cookie or for other cryptographic operations
SECRET_KEY = '<32 bit key>'

# Python standard library log level
LOG_LEVEL = logging.WARN

# Supported values: 'sqlite', 'mysql' or 'postgres'
DB_DRIVER = 'sqlite'

# Host name of the database (ignored for DB_DRIVER = 'sqlite')
DB_HOST = 'database.example.org'

# Name of the Database on the host (for DB_DRIVER = 'sqlite', this is the 'path/to/db.sqlite')
DB_NAME = '/mnt/gnucash/FY_2023.sqlite'

# Supported values: None, 'passthrough'. See below for details.
AUTH_MECHANISM = None

# The maximum number of transactions per page in the ledger
TRANSACTION_PAGE_LENGTH = 25

# Name of the account to be preselected when creating new transactions (optional)
#PRESELECTED_CONTRA_ACCOUNT = 'Example:Account'
```

**Database location**
```
:~# ls -lh /mnt/gnucash/              
total 2.6M
-rwxrw-r-- 1 1005 users 5.8M Sep  9 23:04 FY_2023.sqlite
```

**Comment by joshuabach** [comment]
Hey 79vette!

Can you set `LOG_LEVEL = logging.DEBUG` and post the full output of gnucash-web from start to the error? 

Which version of GnucashWeb are you using? The latest release or the main branch?

**Comment by phil2sat** [comment]
Same here:

`flask run --host=0.0.0.0
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
 * Serving Flask app 'gnucash_web'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.184:5000
Press CTRL+C to quit
 * Restarting with stat
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.
 * Debugger is active!
 * Debugger PIN: 989-854-739
192.168.1.100 - - [12/Sep/2023 14:48:53] "GET /book/accounts/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gnucash_web/auth.py", line 62, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gnucash_web/book.py", line 79, in show_account
    with open_book(
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gnucash_web/utils/gnucash.py", line 73, in open_book
    raise e
  File "/usr/local/lib/python3.11/dist-packages/gnucash_web/utils/gnucash.py", line 66, in open_book
    with piecash.open_book(*args, **kwargs) as book:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/piecash/core/session.py", line 409, in open_book
    raise GnucashException(
piecash._common.GnucashException: Database 'sqlite:///db/gnucash.sqlite' does not exist (please use create_book to create GnuCash books from scratch). If you want to bypass this existence check, use the argument check_exists=False.
192.168.1.100 - - [12/Sep/2023 14:48:53] "GET /book/accounts/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
192.168.1.100 - - [12/Sep/2023 14:48:53] "GET /book/accounts/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
192.168.1.100 - - [12/Sep/2023 14:48:53] "GET /book/accounts/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
192.168.1.100 - - [12/Sep/2023 14:48:53] "GET /book/accounts/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -

/etc/gnucash_web/config.py
import logging

SECRET_KEY = 'FmRAlsBSSqofw/HO/4XaZ639jgW9JDk30dR+85ipv5zs9mVjDWaV36ZM9AKskyfI'

LOG_LEVEL = logging.DEBUG

DB_DRIVER = 'mysql'

DB_HOST = '192.168.1.6'

DB_NAME = 'GnuCash'

AUTH_MECHANISM = None

TRANSACTION_PAGE_LENGTH = 25
`

I neither use sqlite driver, cause i have a mariadb

**Comment by phil2sat** [comment]
OMG, for me i guess it was the missing driver for Python3
pip install mariadb mysql, maybe sqlite3 will fix this

**Comment by phil2sat** [comment]
So found the issue.

its not reading:
/etc/gnucash_web/config.py
or $home/.config/gnucash_web/config.py

Maybe its no longer called so, then please update the install instructions

replaced the /usr/local/lib/python3.11/dist-packages/gnucash_web/config/default.py, error gone

**Comment by joshuabach** [comment]
Yes this is exactly the issue, but it should read those files. So this is likely a bug, but I'm not sure right now why this is happening. Will have to look into it more closely.

This also means that it doesn't even read the `LOG_LEVEL = logging.DEBUG` ...

**Comment by stevemarkham81** [comment]
I had this same issue, and fixed it with the environment variable:

    export GNUCASH_WEB_CONFIG=~/.config/gnucash_web/config.py

**Comment by joshuabach** [comment]
The issue is that the files read by the app are 

```
{~/.config,/etc}/gnucash-web/config.py
```

**and not**

```
{~/.config,/etc}/gnucash_web/config.py
```

as it says in the README (underscore vs. dash).

So this is a documentation bug. Fill fix.
