### ISSUE TITLE
Docker - container access denied

### ISSUE THREAD

**Issue by stevogray** [joshuabach/gnucash-web#53]
I was eagerly awaiting the docker PR to be merged. Tested pulling an image yesterday. Result is:
```
xxxx:~/docker/gnucash$ docker compose up -d
[+] Running 1/1
 ✘ app Error                                                                                                                                                     0.9s
Error response from daemon: Head "https://ghcr.io/v2/joshuabach/gnucash-web/manifests/latest": denied
```
If I request https://ghcr.io/v2/joshuabach/gnucash-web/manifests/latest (same for main and latest) I get a response of:
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}

Google tells me this was a bug a few years ago, fixed by logging out of ghcr.io. Tried that, but it doesn't make any differnce.

Can you please check that the container is public and available for anonymous download?

**Comment by joshuabach** [comment]
I think the problem may be, that the actions are not even running sucessfully, as I have just noticed. I will try to look into that on the weekend

**Comment by joshuabach** [comment]
So, I finally managed to fix everything and it should be working now. Can you try again?

**Comment by stevogray** [comment]
It works (or at least pulls an image)! I had a few false starts because I had tried different version labels. It looks like it needs to be "main". Omitting the label, or using :latest doesn't work in the docker-compose.yaml:

services:
  app:
    image: ghcr.io/joshuabach/gnucash-web:main

  Thanks for looking into this!
